name: react code deployemnt 
# on: [push,workflow_dispatch] 
on: 
 push:
    branches:
        - main  # Trigger on pushes to the main branch
    paths-ignore:
        # - .github/workflows/*  # Ignore changes to this workflow file
 workflow_dispatch:  # Allow manual triggering of the workflow  
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'  # Specify the Node.js version you want to use
            - name: check installed version 
              run: |
                    echo "checking node version"
                    node --version
                    echo "checking npm version"
                    npm --version
            - name: cache dependencies
              uses: actions/cache@v4
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install dependencies
              run: |
                  echo "installing dependencies"
                  npm ci
                  echo "done installing dependencies"
            - name: run tests
              run: |
                  echo "running tests"
                  npm run test
                  echo "done running tests"
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'  
            - name: cache dependencies
              uses: actions/cache@v4
              with:
                 path: ~/.npm
                 key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: install dependecnices
              run: |
                  echo "installing dependencies"
                  npm ci
                  echo "installed dependencies"
            - name: upload artifact
              uses: actions/upload-artifact@v4
             
              with:
                name: build-artifact
                path: dist
            - name: build code 
              run: |
                  echo "building code"
                  npm run build
                  echo "done building code"     
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: donwload artifact
              uses: actions/download-artifact@v4
              with:
                name: build-artifact 
            
                
        #old way to checkout code
        # steps:
            # - name: pull code 
            #   run: |
            #       echo "cloning git repo"
            #       echo "git hub action reserve keyword ${{ toJson(github) }}  }}"
            #       git clone https://github.com/${{ github.repository }}.git 
            #       echo "done cloning"
