name: Greentings
on: push
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "Greet user"
              run: echo "Hello, world!"
            # - name: Checkout code
            #   uses: actions/checkout@v2

            # - name: Greet
            #   run: echo "Hello, world!"
     